AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'client/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/BlockLength:
  Exclude:
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
Style/SymbolArray:
  EnforcedStyle: brackets
