version: 2

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Run Heroku setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "39:55:c3:09:38:f2:ff:d5:75:15:63:a5:2c:54:6d:54"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku run rails db:migrate --app $HEROKU_APP_NAME
            heroku restart --app $HEROKU_APP_NAME

  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: devbadges
          RAILS_ENV: test
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: devbadges
          POSTGRES_DB: devbadges-test
          POSTGRES_PASSWORD: ""

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Bundler dependency cache
          keys:
            - gem-dependencies-{{ checksum "Gemfile.lock" }}
            - gem-dependencies-

      - run:
          name: Install Bundler dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Save Bundler dependency cache
          key: gem-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - restore_cache:
          name: Restore Yarn dependency cache
          keys:
            - yarn-dependencies-{{ checksum "client/yarn.lock" }}
            - yarn-dependencies-

      - run:
          name: Install Yarn dependencies
          command: |
            cd client
            yarn install

      - save_cache:
          name: Save Yarn dependency cache
          key: yarn-dependencies-{{ checksum "client/yarn.lock" }}
          paths:
            - client/node_modules

      - run:
          name: Migrate database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Lint project
          command: |
            rake lint
            cd client
            yarn lint

      - run:
          name: Test project
          command: |
            rake test
            cd client
            yarn test
