default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: devbadges_development

test:
  <<: *default
  database: devbadges_test

production:
  <<: *default
  database: devbadges_production
